In [1]:
import pandas as pd
from canexao import connect_to_mongo

In [2]:
collection_users, collection_tasks = connect_to_mongo()
tabela_users = pd.DataFrame(list(collection_users.find()))
tabela_tasks = pd.DataFrame(list(collection_tasks.find()))

Walkie-Talkie ligado! Estamos conectados ao armário gigante!
a chave do armário é: mongodb+srv://milennasx:Mika0204@cluster0.r08ul.mongodb.net/taskinsight?retryWrites=true&w=majority

In [7]:
tabela_users.head(9)

,_id,name,email,password,papel,departamento,area_atuacao,anos_empresa,formacao_acessibilidade,createdAt,updatedAt,__v
0,6a2b8445cf36b576d237ae6b,Bruno Costa,bruno.costa@focus.com,$2b$10$f9pJiOqzqVhNKLnLIN4v6ueif6Y89L7xdj8Ex7H...,mentorado,Tecnologia,DevBack-end,1,Não,2026-06-12 04:00:05.585,2026-06-12 04:00:05.585,0
1,6a2b8468cf36b576d237ae6c,Felipe Andrade,felipe.andrade@focus.com,$2b$10$n83fHZU1dM6.qkf856tPwOcVHII/WBKsVQYozRe...,mentorado,Tecnologia,QA,1,Não,2026-06-12 04:00:40.910,2026-06-12 04:00:40.910,0
2,6a2b8496cf36b576d237ae6d,Diego Martins,diego.martins@focus.com,$2b$10$/YIzZUbzWkToRC9hY61eTefd/7UMDjLeR1spkv5...,mentorado,Tecnologia,QA,1,Não,2026-06-12 04:01:26.992,2026-06-12 04:01:26.992,0
3,6a2b84b4cf36b576d237ae6e,Camila Lopes,camila.lopes@focus.com,$2b$10$igmoLuOdl9DTW0.krs0TuuFT7axNTJ5HAXcMdwd...,mentorado,Produto,Produto,1,Não,2026-06-12 04:01:56.175,2026-06-12 04:01:56.175,0
4,6a2b84cbcf36b576d237ae6f,Henrique Alves,henrique.alves@focus.com,$2b$10$W1mcbOxpKCrwrT9N9YpltOUpP0A9qv6F4S4XrCi...,mentorado,Produto,UX/UIDesigner,1,Não,2026-06-12 04:02:19.552,2026-06-12 04:02:19.552,0
5,6a2b84ddcf36b576d237ae70,Ana Ribeiro,ana.ribeiro@focus.com,$2b$10$T.mJO1i4ucq17yN0QM30dOLoPIebZIi4rwnTJrv...,mentorado,Tecnologia,Data Engineer,1,Não,2026-06-12 04:02:37.919,2026-06-12 04:02:37.919,0
6,6a2b84eecf36b576d237ae71,Eduarda Souza,eduarda.souza@focus.com,$2b$10$jGAgQvyGq9L1WxfVsaANdeXfqdFuGSvAjZ9/EQC...,mentorado,Tecnologia,DevFront-end,1,Não,2026-06-12 04:02:54.361,2026-06-12 04:02:54.361,0
7,6a2b8501cf36b576d237ae72,Gabriela Pinto,gabriela.pinto@focus.com,$2b$10$CgttUPvLDbeUO0r3wpr8PeQWJ6jccQVlgpMQrXN...,mentorado,Tecnologia,DevMobile,1,Não,2026-06-12 04:03:13.984,2026-06-12 04:03:13.984,0
8,6a2b8b6d17b0933836c1f976,Milenna Xavier,milenna@empresa.com,$2b$10$n.769Tm.vB/SW6/Am04XXeJMVaLcOV3lJ7tzILa...,mentorado,Tecnologia,DevBack-end,1,Sim,2026-06-12 04:30:37.787,2026-06-12 04:30:37.787,0

In [5]:
tabela_users.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   _id                      9 non-null      object
 1   name                     9 non-null      str
 2   email                    9 non-null      str
 3   password                 9 non-null      str
 4   papel                    9 non-null      str
 5   departamento             9 non-null      str
 6   area_atuacao             9 non-null      str
 7   anos_empresa             9 non-null      int64
 8   formacao_acessibilidade  9 non-null      str
 9   createdAt                9 non-null      datetime64[us]
 10  updatedAt                9 non-null      datetime64[us]
 11  __v                      9 non-null      int64
dtypes: datetime64[us](2), int64(2), object(1), str(7)
memory usage: 996.0+ bytes

In [4]:
tabela_tasks.head()

,_id,task_id,titulo,descricao,prioridade,user_id,mentorado,area_atuacao,mentor_responsavel,data_criacao,data_inicio,status_atual,data_conclusao,feedback_conclusao_mentorado,createdAt,updatedAt,__v
0,6a2b884993a2aac46c8ba14a,1.0,Otimizar Microsserviços - Sprint 8,Atividade focada em otimizar o recurso de micr...,media,6a2b8445cf36b576d237ae6b,Bruno Costa,DevBack-end,Juliana Costa,2026-05-05,2026-05-07,andamento,NaT,NaN,NaT,NaT,NaN
1,6a2b884993a2aac46c8ba14b,2.0,Testar Scripts de Deploy - Sprint 2,Atividade focada em testar o recurso de script...,alta,6a2b8468cf36b576d237ae6c,Felipe Andrade,QA,Juliana Costa,2026-03-25,2026-03-27,concluida,2026-04-02,Os testes cobriram os cenários críticos de aut...,NaT,NaT,NaN
2,6a2b884993a2aac46c8ba14c,3.0,Testar Cache em Redis - Sprint 2,Atividade focada em testar o recurso de cache ...,media,6a2b8468cf36b576d237ae6c,Felipe Andrade,QA,Juliana Costa,2026-03-26,2026-03-27,concluida,2026-04-06,Validação executada com sucesso. O fluxo corre...,NaT,NaT,NaN
3,6a2b884993a2aac46c8ba14d,4.0,Testar Componentes React - Sprint 8,Atividade focada em testar o recurso de compon...,media,6a2b8496cf36b576d237ae6d,Diego Martins,QA,Juliana Costa,2026-04-20,2026-04-21,concluida,2026-04-27,Conseguimos manter uma boa cobertura de testes...,NaT,NaT,NaN
4,6a2b884993a2aac46c8ba14e,5.0,Ajustar Exportação de Relatórios - Sprint 3,Atividade focada em ajustar o recurso de expor...,media,6a2b84b4cf36b576d237ae6e,Camila Lopes,Produto,Juliana Costa,2026-03-02,2026-03-05,concluida,2026-03-19,Os ajustes visuais foram concluídos no prazo. ...,NaT,NaT,NaN

In [6]:
tabela_tasks.info()

<class 'pandas.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 17 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   _id                           77 non-null     object
 1   task_id                       76 non-null     float64
 2   titulo                        77 non-null     str
 3   descricao                     77 non-null     str
 4   prioridade                    77 non-null     str
 5   user_id                       77 non-null     object
 6   mentorado                     77 non-null     str
 7   area_atuacao                  76 non-null     str
 8   mentor_responsavel            77 non-null     str
 9   data_criacao                  76 non-null     datetime64[us]
 10  data_inicio                   63 non-null     datetime64[us]
 11  status_atual                  77 non-null     str
 12  data_conclusao                44 non-null     datetime64[us]
 13  feedback_conclusao_mentorado  44 non-null     str
 14  createdAt                     1 non-null      datetime64[us]
 15  updatedAt                     1 non-null      datetime64[us]
 16  __v                           1 non-null      float64
dtypes: datetime64[us](5), float64(2), object(2), str(8)
memory usage: 10.4+ KB